services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - pg
      - redis
    
  pg:
    build: postgres
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./tmp/db_data:/var/lib/postgresql/data

  redis:
    build: redis
    command: redis-server
    ports:
      - '6379:6379'
