development:
  adapter: redis
  url: redis://redis:6379/0
  channel_prefix: instatalk_production

test:
  adapter: redis
  url: redis://redis:6379/0
  channel_prefix: instatalk_production

production:
  adapter: redis
  url: redis://redis:6379/0
  channel_prefix: instatalk_production
